### ISSUE TITLE
[Bug]: style lost with background: var() + background-*

### ISSUE THREAD

**Issue by hb-bobo** [rrweb-io/rrweb#1017]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/rrweb-io/rrweb/issues) for a bug report that matches the one I want to file, without success.

### What package is this bug report for?

rrweb

### Version

v2.0.0-alpha.0 ~ v2.0.0-alpha.3

### Expected Behavior

Example:
```css
:root {
        --red: red;
        --color: var(--red);
}
.box1{
        background: var(--red);
        background-clip: padding-box;
}
```

Expected 

```
.box1{
        background: var(--red);
        background-clip: padding-box;
}
```

### Actual Behavior

```css
    background-image: ;
    background-position-x: ;
    background-position-y: ;
    background-size: ;
    background-repeat-x: ;
    background-repeat-y: ;
    background-attachment: ;
    background-origin: ;
    background-color: ;
    background-clip: padding-box;
```

### Steps to Reproduce

demo code: [https://github.com/hb-bobo/rrweb-microapp/tree/bug/css-var](https://github.com/hb-bobo/rrweb-microapp/tree/bug/css-var)

```
git clone https://github.com/hb-bobo/rrweb-microapp.git
git checkout bug/css-var
yarn
yarn dev
```

![](https://github.com/hb-bobo/rrweb-microapp/blob/bug/css-var/Kapture-css.gif?raw=true)

### Testcase Gist URL

https://github.com/hb-bobo/rrweb-microapp/tree/bug/css-var
