### ISSUE TITLE
rr-block 失效问题

### ISSUE THREAD

**Issue by lxlazy** [rrweb-io/rrweb#771]
基于vue打包后的html内容修改
```html
<input data-v-496f6293 type="text" class="rr-block">
```
对应css样式为属性选择器
```css
input[data-v-496f6293]{
  background: transparent;
}
```
覆盖了自带的rr-block
```css
.rr-block{
  background: currentcolor;
}
```
由于选择器优先级的问题，导致rr-block失效。

PS：页面渲染时，inter平台相比AMD的快太多了，一度以为是自己的BUG
