### ISSUE TITLE
CSS animations applied to pseudo-elements are not paused when player is paused

### ISSUE THREAD

**Issue by JohnPhamous** [rrweb-io/rrweb#775]
Currently we have this rule injected into the player:

```css
 'html.rrweb-paused * { animation-play-state: paused !important; }',
```

This is working as expected. There's an edge case for when an animation is applied to a pseudo-element (`::before` and `::after`).
